#!/usr/bin/env bash

qemu-system-i386 \
  -gdb tcp::1234 -S \
  -m 128M \
  -d cpu_reset,guest_errors \
  -device VGA,vgamem_mb=64 \
  -drive id=disk,file=_disk_image,if=none,format=raw \
  -device ahci,id=ahci\
  -device ide-hd,drive=disk,bus=ahci.0 \
  -kernel ../build/kern.bin
