#!/usr/bin/env bash

qemu-system-i386 \
  -gdb tcp::1235 -S \
  -m 128M \
  -d cpu_reset,guest_errors \
  -drive file=../Scripts/_disk_image,format=raw,index=0,media=disk \
  -device VGA,vgamem_mb=64 \
  -kernel kern.bin
